"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-10-08 07:47:04.775266
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exchange_rates',
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('inr_per_unit', sa.Float(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('currency')
    )
    op.create_table('products',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('canonical_name', sa.Text(), nullable=False),
    sa.Column('brand', sa.String(length=80), nullable=True),
    sa.Column('model', sa.String(length=120), nullable=True),
    sa.Column('category', sa.String(length=80), nullable=True),
    sa.Column('gtin', sa.String(length=14), nullable=True),
    sa.Column('manufacturer_part_number', sa.String(length=80), nullable=True),
    sa.Column('normalized_attributes', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('core_tokens', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('image_hash', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_products_brand_category', 'products', ['brand', 'category'], unique=False)
    op.create_index('ix_products_gtin', 'products', ['gtin'], unique=False)
    op.create_index('ix_products_mpn', 'products', ['manufacturer_part_number'], unique=False)
    op.create_table('retailers',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('key', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('domain', sa.String(length=120), nullable=False),
    sa.Column('country', sa.String(length=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('status_reason', sa.Text(), nullable=True),
    sa.Column('consecutive_failures', sa.Integer(), nullable=False),
    sa.Column('unavailable_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_success_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_failure_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('alert_states',
    sa.Column('product_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('last_alert_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_alert_price', sa.Float(), nullable=True),
    sa.Column('last_alert_discount', sa.Float(), nullable=True),
    sa.Column('last_alert_severity', sa.String(length=10), nullable=True),
    sa.Column('last_alert_retailer', sa.String(length=80), nullable=True),
    sa.Column('miss_count', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('product_id')
    )
    op.create_table('deal_events',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('current_price', sa.Float(), nullable=False),
    sa.Column('baseline_price', sa.Float(), nullable=False),
    sa.Column('discount_percentage', sa.Float(), nullable=False),
    sa.Column('baseline_type', sa.String(length=30), nullable=False),
    sa.Column('best_retailer', sa.String(length=80), nullable=False),
    sa.Column('best_price', sa.Float(), nullable=False),
    sa.Column('deal_score', sa.Float(), nullable=False),
    sa.Column('confidence', sa.String(length=10), nullable=False),
    sa.Column('severity', sa.String(length=10), nullable=False),
    sa.Column('history_quality', sa.String(length=10), nullable=False),
    sa.Column('notification_status', sa.String(length=20), nullable=False),
    sa.Column('details', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_deal_product_ts', 'deal_events', ['product_id', 'detected_at'], unique=False)
    op.create_table('retailer_products',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('retailer_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('retailer_product_id', sa.String(length=160), nullable=False),
    sa.Column('product_url', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('brand', sa.String(length=80), nullable=True),
    sa.Column('category', sa.String(length=80), nullable=True),
    sa.Column('gtin', sa.String(length=14), nullable=True),
    sa.Column('mpn', sa.String(length=80), nullable=True),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('review_count', sa.Integer(), nullable=True),
    sa.Column('availability', sa.Boolean(), nullable=True),
    sa.Column('seller', sa.String(length=160), nullable=True),
    sa.Column('variant', sa.String(length=200), nullable=True),
    sa.Column('mrp_inr', sa.Float(), nullable=True),
    sa.Column('match_confidence', sa.Float(), nullable=True),
    sa.Column('match_notes', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('attributes', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('hot', sa.Boolean(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('last_crawled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_crawl_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('consecutive_failures', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['retailer_id'], ['retailers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('retailer_id', 'retailer_product_id', name='uq_retailer_listing')
    )
    op.create_index('ix_rp_gtin', 'retailer_products', ['gtin'], unique=False)
    op.create_index('ix_rp_next_crawl', 'retailer_products', ['active', 'next_crawl_at'], unique=False)
    op.create_index('ix_rp_product', 'retailer_products', ['product_id'], unique=False)
    op.create_table('daily_prices',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('retailer_product_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('min_price', sa.Float(), nullable=False),
    sa.Column('max_price', sa.Float(), nullable=False),
    sa.Column('last_price', sa.Float(), nullable=False),
    sa.Column('obs_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['retailer_product_id'], ['retailer_products.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('retailer_product_id', 'day', 'source', name='uq_daily_rp_day_src')
    )
    op.create_index('ix_daily_day', 'daily_prices', ['day'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('deal_event_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('channel', sa.String(length=30), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['deal_event_id'], ['deal_events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_notif_deal_channel', 'notifications', ['deal_event_id', 'channel'], unique=True)
    op.create_table('price_observations',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('retailer_product_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('price_inr', sa.Float(), nullable=False),
    sa.Column('shipping_cost', sa.Float(), nullable=False),
    sa.Column('coupon_discount', sa.Float(), nullable=True),
    sa.Column('coupon_verified', sa.Boolean(), nullable=False),
    sa.Column('membership_price', sa.Float(), nullable=True),
    sa.Column('mrp_inr', sa.Float(), nullable=True),
    sa.Column('effective_price', sa.Float(), nullable=False),
    sa.Column('availability', sa.Boolean(), nullable=False),
    sa.Column('is_payable', sa.Boolean(), nullable=False),
    sa.Column('seller', sa.String(length=160), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['retailer_product_id'], ['retailer_products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_obs_rp_ts', 'price_observations', ['retailer_product_id', 'timestamp'], unique=False)
    op.create_index('ix_obs_ts', 'price_observations', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_obs_ts', table_name='price_observations')
    op.drop_index('ix_obs_rp_ts', table_name='price_observations')
    op.drop_table('price_observations')
    op.drop_index('ix_notif_deal_channel', table_name='notifications')
    op.drop_table('notifications')
    op.drop_index('ix_daily_day', table_name='daily_prices')
    op.drop_table('daily_prices')
    op.drop_index('ix_rp_product', table_name='retailer_products')
    op.drop_index('ix_rp_next_crawl', table_name='retailer_products')
    op.drop_index('ix_rp_gtin', table_name='retailer_products')
    op.drop_table('retailer_products')
    op.drop_index('ix_deal_product_ts', table_name='deal_events')
    op.drop_table('deal_events')
    op.drop_table('alert_states')
    op.drop_table('retailers')
    op.drop_index('ix_products_mpn', table_name='products')
    op.drop_index('ix_products_gtin', table_name='products')
    op.drop_index('ix_products_brand_category', table_name='products')
    op.drop_table('products')
    op.drop_table('exchange_rates')
    # ### end Alembic commands ###
